name: Lint and Publish
on: push
jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #need to checkout to run lint?
      - run: |
          npm install; npm run lint
  publish:
    name: Run publish
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JS-DevTools/npm-publish@v1
        with: 
          registry: https://npm.pkg.github.com
          token: ${{ secrets.GITHUB_TOKEN }}


